namespace: default
priorityClass: app-10stars
domain: 'test.devpayever.com'
issue: ''

replicas:
  http: 7

image:
  nginx: registry.devpayever.com/frontend/commerceos
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 80
  monitoringPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 132Mi
  limits:
    memory: 264Mi
hpa:
  cpu:
    tarUti: 75
  mem:
    tarUti: 85
